// unsure if this will map to the pittsburgh geojson neighborhoods dataset
// also, may just be able to use the data served from the backend and format it
export const PITTSBURGH_NEIGHBORHOODS = [
  "All Neighborhoods",
  "Allegheny Center",
  "Allegheny West",
  "Arlington",
  "Arlington Heights",
  "Banksville",
  "Bedford Dwellings",
  "Beechview",
  "Beltzhoover",
  "Bloomfield",
  "Bon Air",
  "Brighton Heights",
  "Brookline",
  "Carrick",
  "Central Business District",
  "Central Lawrenceville",
  "Central Northside",
  "Central Oakland",
  "Chartiers City",
  "Chateau",
  "Crawford-Roberts",
  "Duquesne Heights",
  "East Allegheny",
  "East Carnegie",
  "East Hills",
  "East Liberty",
  "Elliott",
  "Esplen",
  "Fairywood",
  "Fineview",
  "Friendship",
  "Garfield",
  "Glen Hazel",
  "Greenfield",
  "Hays",
  "Hazelwood",
  "Highland Park",
  "Homewood North",
  "Homewood South",
  "Homewood West",
  "Knoxville",
  "Larimer",
  "Lawrenceville",
  "Lincoln Place",
  "Lincoln-Lemington-Belmar",
  "Lower Lawrenceville",
  "Manchester",
  "Marshall-Shadeland",
  "Middle Hill",
  "Morningside",
  "Mount Oliver",
  "Mount Washington",
  "New Homestead",
  "North Oakland",
  "North Point Breeze",
  "North Shore",
  "Northview Heights",
  "Oakwood",
  "Overbrook",
  "Perry North",
  "Perry South",
  "Point Breeze",
  "Point Breeze North",
  "Polish Hill",
  "Regent Square",
  "Ridgemont",
  "Shadyside",
  "Sheraden",
  "South Oakland",
  "South Shore",
  "South Side Flats",
  "South Side Slopes",
  "Spring Garden",
  "Spring Hill-City View",
  "Squirrel Hill North",
  "Squirrel Hill South",
  "St. Clair",
  "Stanton Heights",
  "Strip District",
  "Summer Hill",
  "Swisshelm Park",
  "Terrace Village",
  "Troy Hill",
  "Upper Hill",
  "Upper Lawrenceville",
  "West End",
  "West Oakland",
  "Westwood",
  "Windgap",
];
